### PR TITLE
[Hebrew translation] Fix directory station count

### PR DESCRIPTION
**Pull request by david-levi**
The original translation assumed the `%@` placeholder was a name. However, it turns out that it is a number and so the Hebrew word for "station(s)" should appear after it.

### CODE REVIEW

**Comment by david-levi** [comment]
1) @steventroughtonsmith can you please post a screenshot of the station directory (will all the countries), so I can see this is fixed?
2) See if you can add @orisraeli as reviewer, because GitHub won't let me find him on the list.

**Comment by orisraeli** [comment]
Judging by the commit it looks like it's fixed, but as @david-levi said, a screenshot would be great for verifying.

**Comment by steventroughtonsmith** [comment]
Hey folks, sorry for delayed response, been waiting on an update approval from Apple before I start integrating things for the n+2 update.

How does this look?

Screen Shot 2020-05-15 at 15 41 33

**Comment by david-levi** [comment]
Looks good.

**Pull request merged**
