### PR TITLE
Updated Translation for Certain Words/Phrases

### PR DESCRIPTION
**Pull request by copperisland**

### CODE REVIEW

**Comment by steventroughtonsmith** [comment]
These changes look reasonable; should I merge?

**Comment by copperisland** [comment]
Yes, go ahead. I noticed this [issue](https://github.com/steventroughtonsmith/broadcasts-localization/issues/14) thread after I submitted the pull request but I wasn't sure how to edit again; hence the various requests above. Github newbie problems!

**Comment by steventroughtonsmith** [comment]
Don't worry about it, you're doing great. I made this project its own repository so that it could be as messy as it needed to be 😄

**Comment by copperisland** [comment]
@steventroughtonsmith Thanks for the encouragement! 😅

**Pull request merged**
