### PR TITLE
Small improvements to the French localization

### PR DESCRIPTION
**Pull request by Nicolapps**
— Fix capitalization
— Use neutral language (« Voulez-vous vraiment… » instead of « Ètes-vous sûr », which implies that the user is male)

### CODE REVIEW

**Comment by steventroughtonsmith** [comment]
These changes make sense, thanks! Re WATCH_NOW_PLAYING_TITLE, this is a link to the 'Now Playing' screen, not a status message. Does that change your translation?

**Comment by Nicolapps** [comment]
« Lecture en cours » can also mean _what’s being played_, so I think it’s fit for this case.
Or maybe the simplest translation would be « Lecteur » (i.e. “Player”), would that be accurate?

**Comment by steventroughtonsmith** [comment]
Ideally, this row should have the same title as used in the Music app on Apple Watch; it's not something present in the current version of Broadcasts anyway, but it is something I want to add soon. Thanks!

image

**Comment by Nicolapps** [comment]
They use «&nbsp;À l’écoute&nbsp;» (meaning “Currently being heard”), which sounds the best in French.

Is there a place in the system where TOOLBAR_NOTHING_PLAYING (“Nothing playing”) is used? The current translation doesn’t look very natural, but I couldn’t find anything better. Could «&nbsp;Lecture à l’arrêt&nbsp;» (playing stopped) work instead?

**Comment by steventroughtonsmith** [comment]
It looks like the AirPlay UI has a 'Nothing Playing' equivalent, which might work?

image

**Comment by Nicolapps** [comment]
Thanks for merging!

I don’t have any AirPlay 2 devices at my disposal so I couldn’t check. I’ll try it if I have the opportunity some day.

**Pull request merged**
