### PR TITLE
Update Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by joogps**
This pull request fixes capitalization, updates some terms and adds missing translations.

### CODE REVIEW

**Comment by steventroughtonsmith** [comment]
Thanks João!

**Comment by joogps** [comment]
@steventroughtonsmith You're welcome! If you need to mention my name somewhere, you don't need to include the long last names (only "João Gabriel" is enough 🤣)

**Comment by steventroughtonsmith** [comment]
No problem! How do these look?

Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 03 10 14
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 03 10 16
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 03 10 24
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 03 10 29
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 03 10 44

**Comment by joogps** [comment]
Looks great! There are just a few left-out "or"s (should be "ou"s) in `"WELCOME_COPY"`, `"WELCOME_UPSELL"` and `"UPSELL_COPY"` 😬

**Pull request merged**
