### PR TITLE
Added Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by PBBB**
There are only Simplified Chinese translations so the folder is named "zh-CN".
You can credit me as "PBB" (had to use "PBBB" here at Github because "PBB" was taken 🥺)

### CODE REVIEW

**Comment by steventroughtonsmith** [comment]
Thanks for this! I will get some screenshots done up later so you can see what it's like in the app UI, and verify everything is OK.

**Comment by steventroughtonsmith** [comment]
How do these look?

Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-11 at 18 23 40
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-11 at 18 23 46
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-11 at 18 23 54
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-11 at 18 23 59
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-11 at 18 24 02
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-11 at 18 24 06
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-11 at 18 24 09
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-11 at 18 24 20

**Comment by steventroughtonsmith** [comment]
> There are only Simplified Chinese translations so the folder is named "zh-CN".
> You can credit me as "PBB" (had to use "PBBB" here at Github because "PBB" was taken 🥺)

It looks like Apple uses "zh-Hans" for iOS as the folder name for Chinese (Simplified)

**Comment by PBBB** [comment]
> > There are only Simplified Chinese translations so the folder is named "zh-CN".
> > You can credit me as "PBB" (had to use "PBBB" here at Github because "PBB" was taken 🥺)
> 
> It looks like Apple uses "zh-Hans" for iOS as the folder name for Chinese (Simplified)

I searched about the differences before changing it. As eviljeff said [here](https://github.com/mozilla/addons-server/issues/5829), "zh-CN" is a locale code and "zh-hans" is a language+script code. 

There are both advantages and disadvantages when using "zh-CN" or "zh-hans". Using "zh-hans" (and "zh-hant" for Traditional Chinese) can cover more locales, but however, there are some minor differences in the words between Hong Kong and Taiwan which means the locales should be specified as well. 

And I checked the resources folder of Apple's own apps on macOS (App Store and Pages), and they are using "zh_CN" as you can see in the screenshot below. So I kind of prefer "zh-CN" but "zh-hans" is also totally fine for me.
Screen Shot 2020-05-12 at 07 09 15

By the way, the app UI in Simplified Chinese looks good to me. 🥳

**Comment by steventroughtonsmith** [comment]
Awesome, thanks! I'll include this in the next update

**Pull request merged**
