### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by TheFlow95**
Hi Steven! I follow you on Twitter so I added my native language translation to your app hoping it will help you.

I'm just not just about the capitalization (I followed the english version) but everything else should be fine.

You can credit me as Florentin Bekier

### CODE REVIEW

**Comment by steventroughtonsmith** [comment]
Thanks Florentin! It looks great 😄 Do you know if iOS displays the extra space before " ?" and " !" in other French-localized apps?

**Comment by TheFlow95** [comment]
Great! Yes it does, it's a slighty different typography rule than english

**Comment by steventroughtonsmith** [comment]
Awesome, I'll make sure it's included in the next update

**Comment by steventroughtonsmith** [comment]
Some pictures; does this all look good to you? I will increase the sidebar width for most languages so the 'All Stations' label doesn't get cut off.

Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 02 54 34
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 02 54 36
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 02 54 44
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 02 54 55
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 02 55 02

**Comment by TheFlow95** [comment]
Looks pretty good, it should be perfect with the larger sidebar!

**Comment by steventroughtonsmith** [comment]
Hey Florentin; got some feedback saying "Obtenir de l’aide sur Twitter" would be more appropriate for MENU_HELP_GETSUPPORT — do you agree? Thanks!

**Comment by TheFlow95** [comment]
Yeah I think it makes more sense, "support" is a word we use sometimes as an anglicism but "Obtenir de l’aide sur Twitter" is more accurate for everybody to understand

**Pull request merged**
