### PR TITLE
Spanish (Spain) translation

### PR DESCRIPTION
**Pull request by atnbueno**

### CODE REVIEW

**Comment by steventroughtonsmith** [comment]
This looks great, thank you! Can I credit you as "Antonio Bueno"?

**Comment by atnbueno** [comment]
> [...] Can I credit you as "Antonio Bueno"?
Yes, thanks for asking

**Comment by steventroughtonsmith** [comment]
Hi Antonio; had feedback on Twitter that "Obtener apoyó en Twitter" might be a better translation for MENU_HELP_GETSUPPORT — would you agree with this change? Thanks!

**Comment by atnbueno** [comment]
"apoyo" and "soporte" are [synonymous](https://www.wordreference.com/sinonimos/soporte). But in the sense of getting help, at least in technical issues, "soporte" is the word used (as in "soporte técnico", technical support). Example:
https://support.apple.com/es-es/contact

**Comment by steventroughtonsmith** [comment]
Great thread & reasoning on Twitter; I will leave it as you’ve written. Thanks!

**Pull request merged**
