### PR TITLE
Updated Russian Localization

### PR DESCRIPTION
**Pull request by mrob2t**
Swapped translations for show/hide sidebar menu items, didn't notice this issue yesterday. 
Also, made a few changes which address possible ambiguity.

### CODE REVIEW

**Comment by mrob2t** [comment]
Could you please show how WELCOME_ADD_PRESETS currently looks in the Russian version of the app? I'm concerned that it might be too long.

**Comment by steventroughtonsmith** [comment]
This is what it looks like currently; it's long, but it does fit. Is there a better way to phrase this?

Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-11 at 15 37 54

**Comment by mrob2t** [comment]
A possible solution is to translate "Add Presets" as "Add Stations" and make changes to WELCOME_COPY and WELCOME_UPSELL, so that users will understand that "Stations" refers to the _**preset**_ stations.

For example, "If you'd like, we have some preset stations from our home that we can start your library with." could be translated as "Would you like to add our preset stations from Ireland? They will help you to start your library." 

So the app will ask a direct question thus making it clear what the buttons do. Is it OK?

**Comment by steventroughtonsmith** [comment]
I would, for now, keep things as 'presets', as I know users don't read the description and will just trust the button to tell them what's happening. Minor changes to the meaning of the onboarding/upsell dialogs to get it where it is today has dramatically decreased the amount of support requests & confused store reviews I get. I worry that making it 'Add Stations' would just increase the confusion level

**Comment by mrob2t** [comment]
I've discussed this with my Russian-speaking friends and managed to shorten the text by 4 letters while keeping it as 'presets'. Should look a bit better now. I'm afraid, it can't be shorter than that.

**Comment by mrob2t** [comment]
By the way, is it required to preserve the capitalization of "Directory"? To be honest, I'm not even sure why it's capitalized :)

**Comment by steventroughtonsmith** [comment]
Great, thanks!

Different languages have different rules about this in iOS; for English, the Directory is a named feature of the app, like Station, or Collection. As such, it gets title case whenever I reference it in the UI. I know this is not the case for every locale

**Comment by mrob2t** [comment]
Thank you, now I get it.

**Comment by mrob2t** [comment]
Everything's ready to be merged. 
Taking part in localization has been a great experience, thank you for this opportunity!

**Comment by steventroughtonsmith** [comment]
Thanks for the update! Will include these changes in the next update (1.3.5). The existing Russian translation & credits should be live in v1.3.4 now.

**Pull request merged**
