### PR TITLE
Greek Translation

### PR DESCRIPTION
**Pull request by copperisland**
Thanks!

-Pavlos

### CODE REVIEW

**Comment by steventroughtonsmith** [comment]
Thanks Pavlos! What name should I credit you by?

**Comment by copperisland** [comment]
Pavlos is fine. It's my first time on GitHub so I hope this is ok. :-)

**Comment by steventroughtonsmith** [comment]
Looks good to me! I'll merge it and take some screenshots so you can verify

**Comment by steventroughtonsmith** [comment]
Ok, how do these look:

Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 03 24 25
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 03 24 43
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 03 24 48
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 03 24 53
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 03 25 17

**Comment by copperisland** [comment]
Looking good! I just need to capitalise "or" in the first screenshot.

**Pull request merged**
