### PR TITLE
Added german translation

### PR DESCRIPTION
**Pull request by ocastx**

### CODE REVIEW

**Comment by steventroughtonsmith** [comment]
Thanks Sebastian! This looks good here

**Comment by steventroughtonsmith** [comment]
How do these look to you?

Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 15 39 22
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 15 39 31
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 15 39 37
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 15 39 41
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 15 39 53

**Comment by ocastx** [comment]
Looks good!

Just a small thing on screen 2: The search bar hint states: „Suche Länder“ which was translated from „Search countries“

This is unusual I would say for iOS apps. I looked into the Apple Music app which states „Artists, Songs, Playlists“ („Künstler, Titel, Playlists“ in german)

Calendar app just states: „Search“

So I would rather correct it to either
1. Just „Search“ („Suchen“)
2. or „Countries“ („Länder“)

But it‘s only a small thing, your choice :)

**Comment by steventroughtonsmith** [comment]
The Search Countries/Search Stations distinction is because that panel has two different kinds of search. It's more of a filter right now, but I'll probably change that in the future.

So perhaps it's good to keep it the way you've translated it, and whenever I change the function of the search bar I can remap it to the SEARCH_PLACEHOLDER string, which is just Suche. How does that sound?

**Comment by ocastx** [comment]
Sounds good 👍

**Pull request merged**
