### PR TITLE
Add Indonesian localization file

### PR DESCRIPTION
**Pull request by jiprastyo**

### CODE REVIEW

**Comment by steventroughtonsmith** [comment]
Thanks for this! What name can I credit you by?

**Comment by jiprastyo** [comment]
> Thanks for this! What name can I credit you by?
'Prastyo' should be fine.


> Thanks for this! What name can I credit you by?

**Comment by steventroughtonsmith** [comment]
Awesome, thanks!

**Comment by steventroughtonsmith** [comment]
How do these look to you:

Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 18 29 24
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 18 29 27
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 18 29 36
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 18 29 42
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 18 29 44
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 18 29 50

**Pull request merged**
