### PR TITLE
Add Romanian translation

### PR DESCRIPTION
**Pull request by AndreiVidrasco**

### CODE REVIEW

**Comment by steventroughtonsmith** [comment]
Happy to merge this; are there any changes you'd want to make, based on the discussion in the other thread?

**Comment by AndreiVidrasco** [comment]
So, checked again. I couldn't find any typos and I used here different capitalization than with russian.
Regards special cases, there aren't such cases in romanian, like the ones we had in russian.

only thing that might require changes, in my opinion, are the ones with long text.
Grammatically they are correct, but my language is not so poetic and I'm pretty sure someone would write it more nicely than me
WELCOME_COPY
WELCOME_UPSELL
UPSELL_COPY

**Comment by steventroughtonsmith** [comment]
In lieu of a second Romanian speaker to check this over, I'll take some screenshots and then can merge this as-is, and let changes come later. How does that sound?

**Comment by AndreiVidrasco** [comment]
Was thinking about the same. We can always change later, in cases we find better wording

**Comment by steventroughtonsmith** [comment]
Screenshots:

Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-10 at 20 20 17
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-10 at 20 20 22
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-10 at 20 20 32
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-10 at 20 20 36
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-10 at 20 20 39
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-10 at 20 20 45
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-10 at 20 20 48
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-10 at 20 20 52

**Comment by AndreiVidrasco** [comment]
Ok, did some additional updates. Now it's good to merge.

**Comment by steventroughtonsmith** [comment]
Sweet, thanks!

**Pull request merged**
