### PR TITLE
Fixed typos and rephrased certain words

### PR DESCRIPTION
**Pull request by copperisland**
Fixed typos and rephrased certain words to improve the translation.

Would it be possible to see screenshots of the app with the updated translations? I removed the capitalisation of certain words and I want to make sure that it looks consistent.

### CODE REVIEW

**Comment by steventroughtonsmith** [comment]
Sure thing; how does this look?

Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-06-04 at 15 15 53
Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-06-04 at 15 15 44
Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-06-04 at 15 15 42
Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-06-04 at 15 15 39
Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-06-04 at 15 15 36
Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-06-04 at 15 15 13
Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-06-04 at 15 15 06
Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-06-04 at 15 15 04

**Comment by copperisland** [comment]
It looks good. If it's not too much trouble, could you please show me how:

"STATION_DIRECTORY_STATIONS" = 
and 
"STATION_DIRECTORY_STATIONS_PLURAL" = 

look like before merging?

**Comment by steventroughtonsmith** [comment]
Sure, that would be the subtitles of these table cells:

Screen Shot 2020-06-04 at 16 37 28

**Comment by copperisland** [comment]
Thanks, it looks ok. You can merge the changes. 😃

**Comment by steventroughtonsmith** [comment]
Sweet; it'll be included in the next update to Broadcasts (1.3.6). Thanks!

**Pull request merged**
