### PR TITLE
Add Ukrainian localisation

### PR DESCRIPTION
**Pull request by haawa799**

### CODE REVIEW

**Comment by steventroughtonsmith** [comment]
Thanks Andrii! Do you wish to be credited as "Andrii K.", or would you prefer a longer form?

**Comment by haawa799** [comment]
Andrii K. works fine for me)

**Comment by steventroughtonsmith** [comment]
OK, great. How do these look to you?

Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 15 36 21
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 15 36 35
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 15 36 40
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 15 36 44
Simulator Screen Shot - iPad Pro (11-inch) - 2020-05-09 at 15 36 49

**Comment by haawa799** [comment]
Looks great 👌

**Pull request merged**
