### PR TITLE
Updated Russian Translation

### PR DESCRIPTION
**Pull request by tvrrp**
Added translation for the new version. 
Corrected the translation of old phrases that looked complicated in Russian.

### CODE REVIEW

**Comment by tvrrp** [comment]
P.S. Does the line about native pixel scaling really have to be there? If I were a normal user, I would have absolutely no idea what it is. It seems to me that this information is a bit useless. In addition, it cannot be properly translated into Russian 😀

**Comment by steventroughtonsmith** [comment]
> P.S. Does the line about native pixel scaling really have to be there? If I were a normal user, I would have absolutely no idea what it is. It seems to me that this information is a bit useless. In addition, it cannot be properly translated into Russian 😀

It needed to be there for v2.0, as it was a major component of the transition from older versions of the app to current (and a top user request). However, it's part of the new features screen that won't be shown again until v3.0 comes and changes all the 'new features', so at this point doesn't need to be translated. Thanks!

**Comment by steventroughtonsmith** [comment]
This looks good for v2.2; would you like to be credited as 'Damir Yackupov', or do you have something you prefer? Thanks!

**Comment by tvrrp** [comment]
> This looks good for v2.2; would you like to be credited as 'Damir Yackupov', or do you have something you prefer? Thanks!

Yes, I'd like to

**Pull request merged**
